---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-5.9
- name: centos-6.5
- name: ubuntu-12.04
- name: debian-7.1.0

suites:
- name: clients
  run_list:
    - recipe[base-box-prep]
    - recipe[mariadb::client]
  attributes:
